### ISSUE TITLE
Translation / arrow control

### ISSUE THREAD

**Issue by larissa-n** [sasza2/arrows#13]
This is a really neat library. Would there be a way to add more options to control arrows? The translation property is documented as a function of position relative to viewport, but maybe setting arrow direction as an absolute angle would be more straightforward?

Here's an example, the translation property is identical for all arrows:

<img width="759" alt="Screen Shot 2020-09-19 at 11 40 52 AM" src="https://user-images.githubusercontent.com/37840830/93670946-47d35e00-fa9f-11ea-8d14-350eb39b9978.png">

https://codesandbox.io/s/strange-mahavira-hwfex?file=/src/App.js

**Comment by sasza2** [comment]
Thank you. You're right, currently it's not working as it should, my bad. 

In your example it should looks like:

![Zrzut ekranu z 2020-09-19 18-43-13](https://user-images.githubusercontent.com/30594281/93676428-87547700-faac-11ea-9781-3225968940d4.png)

^ because **from** translation goes left (-1) + top (-1) and **to** goes right (1) + top (-1)

I've created branch https://github.com/sasza2/arrows/tree/bugfix/arrow-prevent-relative-position-of-parent-and-scroll-larissa-n
with your example https://github.com/sasza2/arrows/tree/bugfix/arrow-prevent-relative-position-of-parent-and-scroll-larissa-n/test/translation

Could you look if it's now matching your use case? Just run **npm run install** and then **npm run build**

I've changed translations a little bit to:
```
from: {
  node: prevNode,
  direction: 'right',
  translation: [0.25, 1]
},
to: {
  node: currNode,
  direction: 'left',
  translation: [-0.25, 1]
},
```

Result:
![Zrzut ekranu z 2020-09-19 19-14-57](https://user-images.githubusercontent.com/30594281/93676436-87ed0d80-faac-11ea-9f12-260f000b67f8.png)

**Comment by larissa-n** [comment]
Thank you for your fast response, those look like exactly the right changes!
