### ISSUE TITLE
Why setinterval instead of requestanimationframe

### ISSUE THREAD

**Issue by CKGrafico** [sasza2/arrows#42]
Hello and thanks for your library,
I'm checking the code and I'm curious about why you're using set interval instead of requestanimationframe.

https://github.com/sasza2/arrows/blob/f5286069b3f9e77b700c5fa5527d41ca8e3f6ec3/src/observer/observer.ts#L57

**Comment by sasza2** [comment]
Hi @CKGrafico, thanks! When I was writing that library I assumed that arrow shape would not change too often (`from` and `to` position would be same during lifecycle of an application). also I didn't want calculations to be too heavy for browser. If you want arrow to refresh faster there is a prop `updateDelay`.
You are just curious or you have some case where you need to render faster? because we can easily apply requestAnimationFrame() if needed

**Comment by CKGrafico** [comment]
Hello! Yes I'm not just curious :D Right now is not a huge performance problem but I'm combining this with a scroll animations library and when the users scroll the `from` `to` are animated an then the arrows are moving :)

**Comment by sasza2** [comment]
Okay, I've made some changes in latest version (1.5.6). If you pass to `arrowCreate({ ..., updateDelay: 0 }),` it would run `requestAnimationFrame(cb)` instead of `setInterval(cb, updateDelay)`. Does it fit your requirements?

**Comment by CKGrafico** [comment]
Awesome, thanks!

**Comment by sasza2** [comment]
you're welcome
